version: '3'
# https://dev.to/aschmelyun/the-beauty-of-docker-for-local-laravel-development-13c0
networks:
  laravel:

services:
  # The Web Server
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    working_dir: /var/www
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - .docker/laravel.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysqldb
    networks:
      - laravel

  # The Database
  mysqldb:
    image: mysql:5.7
    container_name: mysqldb
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=laravel"
      - "MYSQL_USER=root"
      - "MYSQL_PASSWORD=root"
      - "MYSQL_ROOT_PASSWORD=root"
    networks:
      - laravel

  # PHP 7.3
  php:
    build:
      context: ./
      dockerfile: .docker/Dockerfile
    volumes:
      - ./:/var/www
    ports:
      - "9000:9000"
    networks:
      - laravel
volumes:
  dbdata: